# The name of your Flutter project.
name: kurakani

# A short description of your app.
description: "A new Flutter project."

# This line prevents accidental publishing to pub.dev (remove it if you want to publish).
publish_to: 'none'

# Version number of your app: format is major.minor.patch+build
version: 1.0.0+1

# Specify the Dart SDK version required to run this app.
environment:
  sdk: ^3.8.1

# ------------- 📦 PROJECT DEPENDENCIES -------------
dependencies:
  # Flutter SDK itself.
  flutter:
    sdk: flutter

  # Date/time formatting and internationalization.
  intl: ^0.18.0

  # Cupertino (iOS-style) icons support.
  cupertino_icons: ^1.0.8

  # Firebase core services initialization.
  firebase_core: ^3.14.0

  # Firebase Authentication support.
  firebase_auth: ^5.6.0

  # Cloud Firestore database.
  cloud_firestore: ^5.6.9

  # Provider for state management (e.g., theming, auth).
  provider: ^6.1.5

# ------------- 🔧 DEV DEPENDENCIES (for dev/test tooling) -------------
dev_dependencies:
  # Flutter unit and widget test framework.
  flutter_test:
    sdk: flutter

  # Recommended linting rules for good coding practices.
  flutter_lints: ^5.0.0

  # Dev tool to automatically generate app launcher icons.
  flutter_launcher_icons: ^0.13.1


# ------------- 🎨 FLUTTER-SPECIFIC CONFIGURATIONS -------------
flutter:

  # Enables using Material Icons.
  uses-material-design: true

  # Declares image assets so they can be used in the app.
  assets:
    - assets/  # Loads all assets inside the assets/ folder

# ------------- 🚀 APP ICON GENERATION CONFIG -------------
# This is used by the flutter_launcher_icons package.
flutter_launcher_icons:
  android: true        # Generate icons for Android
  ios: true            # Generate icons for iOS
  image_path: "assets/icon/app_icon.png"  # Path to your 1024x1024 icon image
