// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmrKZ274O4ed1SRdfRffgW2uxIy6QQJUk',
    appId: '1:473259155788:web:6135e87d06daa4dc27efe9',
    messagingSenderId: '473259155788',
    projectId: 'kurakani-e159c',
    authDomain: 'kurakani-e159c.firebaseapp.com',
    storageBucket: 'kurakani-e159c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHPUOLs6JZjBgMJqdFVrokVbLI2e3oD0w',
    appId: '1:473259155788:android:c537979002d5157027efe9',
    messagingSenderId: '473259155788',
    projectId: 'kurakani-e159c',
    storageBucket: 'kurakani-e159c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPfxnixBluxz_NgKhrqe3KPdC5RwVBVZM',
    appId: '1:473259155788:ios:cdc9cdb1a348ec7727efe9',
    messagingSenderId: '473259155788',
    projectId: 'kurakani-e159c',
    storageBucket: 'kurakani-e159c.firebasestorage.app',
    iosBundleId: 'com.example.kurakani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPfxnixBluxz_NgKhrqe3KPdC5RwVBVZM',
    appId: '1:473259155788:ios:cdc9cdb1a348ec7727efe9',
    messagingSenderId: '473259155788',
    projectId: 'kurakani-e159c',
    storageBucket: 'kurakani-e159c.firebasestorage.app',
    iosBundleId: 'com.example.kurakani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmrKZ274O4ed1SRdfRffgW2uxIy6QQJUk',
    appId: '1:473259155788:web:9509e377a48e520027efe9',
    messagingSenderId: '473259155788',
    projectId: 'kurakani-e159c',
    authDomain: 'kurakani-e159c.firebaseapp.com',
    storageBucket: 'kurakani-e159c.firebasestorage.app',
  );
}
